### PR TITLE
Refactor for compatibility with pl-concat

### PR DESCRIPTION
**Pull request by bmjen**
Updates file_concat with the necessary params to be compatible with puppetlabs-concat.
In the process of refactoring some of this, we also chose a path where the easiest solution -- rather than copying functions from type/file.rb -- we generated a File type and pass it the params, so that File can handle all of the heavy lifting.

### CODE REVIEW

**Comment by electrical** [comment]
Acceptance testing looks good. Centos-7 fails but is expected.

**Comment by bmjen** [comment]
jenkins, test it

**Comment by electrical** [comment]
Its still the centos-7 stuff thats failing. Will remove it from the matrix for now

**Comment by electrical** [comment]
@bmjen if you could add the documentation update on this PR as well i'll merge it.
Thanks!

**Comment by electrical** [comment]
If you rebase with master it will include the centos-7 acceptance stuff and should work from now on.

**Comment by electrical** [comment]
jenkins, test it

**Comment by bmjen** [comment]
jenkins, test it

**Comment by bmjen** [comment]
jenkins, test it

**Comment by electrical** [comment]
Looks like it all works here, How are the concat tests looking with this branch?

**Pull request merged**
