### PR TITLE
adds windows support

### PR DESCRIPTION
**Pull request by bmjen**

### CODE REVIEW

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
jenkins, test it

**Comment by bmjen** [comment]
jenkins, test it

**Comment by bmjen** [comment]
jenkins, test it

**Comment by electrical** [comment]
jenkins, test it

**Comment by bmjen** [comment]
jenkins, test it

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
Took a while but its in! :-)

**Pull request merged**
